code --install-extension alphabotsec.vscode-eclipse-keybindings
code --install-extension codezombiech.gitignore
code --install-extension cschlosser.doxdocgen
code --install-extension dbaeumer.jshint
code --install-extension dbaeumer.vscode-eslint
code --install-extension DigitalBrainstem.javascript-ejs-support
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension felipecaputo.git-project-manager
code --install-extension Kelvin.vscode-sshfs
code --install-extension liximomo.remotefs
code --install-extension MS-CEINTL.vscode-language-pack-es
code --install-extension ms-vscode.cpptools
code --install-extension nobuhito.printcode
code --install-extension patrys.vscode-code-outline
code --install-extension pkosta2005.heroku-command
code --install-extension platformio.platformio-ide
code --install-extension robertohuertasm.vscode-icons
